const { Schema, model } = require("mongoose");

const festivalSchema = new Schema({
  name: {
    type: String,
    unique: true,
    required: true,
  },
  image: {
    type: String,
    default:
      "https://images.ecestaticos.com/V-BFQif9aRCJoj_W4WxB8ffFgkE=/49x0:2211x1622/557x418/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2Fdc8%2F0bd%2Ff1c%2Fdc80bdf1cc8349bcb6d17e68096603b9.jpg",
  },
  startDate: {
    type: Date,
    required: true,
  },
  endDate: {
    type: Date,
    required: true,
  },
  city: {
    type: String,
    required: true,
    enum: [
      "Madrid",
      "Barcelona",
      "Sevilla",
      "Málaga",
      "Valencia",
      "Bilbao",
      "Zaragoza",
      "Murcia",
      "Palma",
      "Las Palmas",
      "Alicante",
      "Córdoba",
      "Valladolid",
      "Vigo",
      "Gijón",
      "Vitoria-Gasteiz",
      "A Coruña",
      "Elche",
      "Granada",
      "Tarrasa",
      "Badalona",
      "Petrel",
      "Oviedo",
      "Cartagena",
      "Sabadell",
      "Jerez de la Frontera",
      "Móstoles",
      "Santa Cruz",
      "Pamplona",
      "Almería",
      "Alcalá de Henares",
      "Fuenlabrada",
      "Donostia",
      "Leganés",
      "Getafe",
      "Burgos",
      "Albacete",
      "Castellón de la Plana",
      "Santander",
      "Alcorcón",
      "Guadalajara",
      "La Laguna",
      "Logroño",
      "Marbella",
      "Badajoz",
      "Salamanca",
      "Huelva",
      "Lleida",
      "Dos Hermanas",
      "Tarragona",
      "Torrejón de Ardoz",
      "Parla",
      "Mataró",
      "Algeciras",
      "León",
      "Alcobendas",
      "Cádiz",
      "Jaén",
      "Reus",
      "Ourense",
      "Roquetas de Mar",
      "Telde",
      "Girona",
      "San Vicente de Baracaldo",
      "Santiago de Compostela",
      "San Cugat del Vallés",
      "Las Rozas de Madrid",
      "San Fernando",
      "San Sebastián de los Reyes",
      "Ciudad de Melilla",
      "Toledo",
      "Torrente",
      "San Baudilio de Llobregat",
      "Torrevieja",
      "Ciudad de Ceuta",
      "Fuengirola",
      "Arona",
      "Valdemoro",
      "Rubí",
      "Manresa",
      "Avilés",
      "Gandía",
      "Benalmádena",
      "Majadahonda",
      "Paterna",
      "Benidorm",
      "Torremolinos",
      "Villanueva y Geltrú",
      "Castelldefels",
      "Viladecáns",
      "El Prat de Llobregat",
      "Arrecife",
      "Collado-Villalba",
      "La Línea de la Concepción",
      "Irún",
      "Boadilla del Monte",
      "Granollers",
      "Mérida",
      "San Vicente del Raspeig",
      "Elda",
      "Mollet",
      "Torrelavega",
      "Ibiza",
      "Rincón de la Victoria",
      "Vich",
      "Mairena del Aljarafe",
      "Figueras",
      "Gavá",
      "Esplugas de Llobregat",
      "Santurce-Antiguo",
      "San Felíu de Llobregat",
      "Portugalete",
      "Mislata",
      "Alcantarilla",
      "Igualada",
      "Blanes",
      "Villafranca del Panadés",
      "San Fernando de Henares",
      "Vendrell",
      "Burjasot",
      "Arucas",
      "Ripollet",
      "San Adrián de Besós",
      "Moncada",
      "Olot",
      "Cambrils",
      "Azuqueca de Henares",
      "Arroyomolinos",
      "Villajoyosa",
      "San Juan Despí",
      "Aldaya",
      "Salt",
      "Manises",
      "Durango",
      "Alacuás",
      "Calafell",
      "Salou",
      "Martorell",
      "Catarroja",
      "Premiá de Mar",
      "San Vicente dels Horts",
      "Sestao",
      "Camas",
      "San Andrés de la Barca",
      "San Pedro del Pinatar",
      "Paiporta",
      "Molíns de Rey",
      "Santa Perpetua de Moguda",
      "Tomares",
      "Alboraya",
      "Torrelodones",
      "Armilla",
      "Erandio",
      "San Juan de Alicante",
      "Olesa de Montserrat",
      "Calpe",
      "Mejorada del Campo",
      "Zarautz",
      "Vilaseca de Solcina",
      "Bormujos",
      "Maracena",
      "San Felíu de Guixols",
      "San Juan de Aznalfarache",
      "Moncada",
      "Alfafar",
      "San Juan de Vilasar",
      "Palafrugell",
      "Manlleu",
      "Puzol",
      "Bañolas",
      "Barañáin",
      "Humanes de Madrid",
      "Sant Just Desvern",
      "Archena",
      "Calella",
      "La Corredoría",
      "Malgrat de Mar",
      "Utebo",
      "Cardedeu",
      "Palamós",
      "El Astillero",
      "Castilleja de la Cuesta",
      "Torredembarra",
      "Guernica y Luno",
      "Canovellas",
      "Albal",
    ],
  },
  region: {
    type: String,
    required: true,
    enum: [
      "Andalucía",
      "Aragón",
      "Asturias",
      "Cantabria",
      "Castilla-La Mancha",
      "Castilla y León",
      "Cataluña",
      "Comunidad Valenciana",
      "Extremadura",
      "Galicia",
      "Islas Baleares",
      "Islas Canarias",
      "La Rioja",
      "Madrid",
      "Murcia",
      "Navarra",
      "País Vasco",
      "Ceuta",
      "Melilla",
    ],
  },
  artists: {
    type: [String],
  },
  genres: {
    type: [String],
    enum: [
      "pop",
      "rock",
      "indie",
      "alternativo",
      "urbano",
      "reggae",
      "folk",
      "urbano",
      "hip hop",
      "reggaeton",
    ],
  },
  minPrize: {
    type: Number,
    min: 0,
  },
  campingArea: {
    type: Boolean,
  },
  extraInfo: {
    type: String,
  },
});

const Festival = model("Festival", festivalSchema);

module.exports = Festival;
